// Code generated by protoc-gen-go. DO NOT EDIT.
// source: action/action.proto

package action // import "git.helloworld.icu/proto/token/action"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// used as a grpc error code
type RespCode int32

const (
	RespCode_OK                  RespCode = 0
	RespCode_INVALID_ADDRESS     RespCode = 21
	RespCode_INVALID_REQID       RespCode = 22
	RespCode_TRANSACTION_HANDING RespCode = 23
)

var RespCode_name = map[int32]string{
	0:  "OK",
	21: "INVALID_ADDRESS",
	22: "INVALID_REQID",
	23: "TRANSACTION_HANDING",
}
var RespCode_value = map[string]int32{
	"OK":                  0,
	"INVALID_ADDRESS":     21,
	"INVALID_REQID":       22,
	"TRANSACTION_HANDING": 23,
}

func (x RespCode) String() string {
	return proto.EnumName(RespCode_name, int32(x))
}
func (RespCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_action_90ba77703ae0bf49, []int{0}
}

type TransCode int32

const (
	TransCode_UNKNOW  TransCode = 0
	TransCode_PENDING TransCode = 1
	TransCode_DONE    TransCode = 2
	TransCode_DROPPED TransCode = 3
)

var TransCode_name = map[int32]string{
	0: "UNKNOW",
	1: "PENDING",
	2: "DONE",
	3: "DROPPED",
}
var TransCode_value = map[string]int32{
	"UNKNOW":  0,
	"PENDING": 1,
	"DONE":    2,
	"DROPPED": 3,
}

func (x TransCode) String() string {
	return proto.EnumName(TransCode_name, int32(x))
}
func (TransCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_action_90ba77703ae0bf49, []int{1}
}

type AccountRequest struct {
	Password             string   `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountRequest) Reset()         { *m = AccountRequest{} }
func (m *AccountRequest) String() string { return proto.CompactTextString(m) }
func (*AccountRequest) ProtoMessage()    {}
func (*AccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_action_90ba77703ae0bf49, []int{0}
}
func (m *AccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountRequest.Unmarshal(m, b)
}
func (m *AccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountRequest.Marshal(b, m, deterministic)
}
func (dst *AccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountRequest.Merge(dst, src)
}
func (m *AccountRequest) XXX_Size() int {
	return xxx_messageInfo_AccountRequest.Size(m)
}
func (m *AccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AccountRequest proto.InternalMessageInfo

func (m *AccountRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AccountResponse struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountResponse) Reset()         { *m = AccountResponse{} }
func (m *AccountResponse) String() string { return proto.CompactTextString(m) }
func (*AccountResponse) ProtoMessage()    {}
func (*AccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_action_90ba77703ae0bf49, []int{1}
}
func (m *AccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountResponse.Unmarshal(m, b)
}
func (m *AccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountResponse.Marshal(b, m, deterministic)
}
func (dst *AccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountResponse.Merge(dst, src)
}
func (m *AccountResponse) XXX_Size() int {
	return xxx_messageInfo_AccountResponse.Size(m)
}
func (m *AccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AccountResponse proto.InternalMessageInfo

func (m *AccountResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type GetBalanceRequest struct {
	ContractAddr         string   `protobuf:"bytes,1,opt,name=contractAddr,proto3" json:"contractAddr,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Symbol               string   `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBalanceRequest) Reset()         { *m = GetBalanceRequest{} }
func (m *GetBalanceRequest) String() string { return proto.CompactTextString(m) }
func (*GetBalanceRequest) ProtoMessage()    {}
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_action_90ba77703ae0bf49, []int{2}
}
func (m *GetBalanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBalanceRequest.Unmarshal(m, b)
}
func (m *GetBalanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBalanceRequest.Marshal(b, m, deterministic)
}
func (dst *GetBalanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBalanceRequest.Merge(dst, src)
}
func (m *GetBalanceRequest) XXX_Size() int {
	return xxx_messageInfo_GetBalanceRequest.Size(m)
}
func (m *GetBalanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBalanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBalanceRequest proto.InternalMessageInfo

func (m *GetBalanceRequest) GetContractAddr() string {
	if m != nil {
		return m.ContractAddr
	}
	return ""
}

func (m *GetBalanceRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *GetBalanceRequest) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

type GetBalanceResponse struct {
	Balance              string   `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	Decimal              uint32   `protobuf:"varint,2,opt,name=decimal,proto3" json:"decimal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBalanceResponse) Reset()         { *m = GetBalanceResponse{} }
func (m *GetBalanceResponse) String() string { return proto.CompactTextString(m) }
func (*GetBalanceResponse) ProtoMessage()    {}
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_action_90ba77703ae0bf49, []int{3}
}
func (m *GetBalanceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBalanceResponse.Unmarshal(m, b)
}
func (m *GetBalanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBalanceResponse.Marshal(b, m, deterministic)
}
func (dst *GetBalanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBalanceResponse.Merge(dst, src)
}
func (m *GetBalanceResponse) XXX_Size() int {
	return xxx_messageInfo_GetBalanceResponse.Size(m)
}
func (m *GetBalanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBalanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBalanceResponse proto.InternalMessageInfo

func (m *GetBalanceResponse) GetBalance() string {
	if m != nil {
		return m.Balance
	}
	return ""
}

func (m *GetBalanceResponse) GetDecimal() uint32 {
	if m != nil {
		return m.Decimal
	}
	return 0
}

type TransactionRequest struct {
	ReqID                string   `protobuf:"bytes,1,opt,name=reqID,proto3" json:"reqID,omitempty"`
	ContractAddr         string   `protobuf:"bytes,2,opt,name=contractAddr,proto3" json:"contractAddr,omitempty"`
	Amount               string   `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	From                 string   `protobuf:"bytes,5,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,6,opt,name=to,proto3" json:"to,omitempty"`
	Memo                 string   `protobuf:"bytes,7,opt,name=memo,proto3" json:"memo,omitempty"`
	Symbol               string   `protobuf:"bytes,8,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Precision            uint32   `protobuf:"varint,9,opt,name=precision,proto3" json:"precision,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionRequest) Reset()         { *m = TransactionRequest{} }
func (m *TransactionRequest) String() string { return proto.CompactTextString(m) }
func (*TransactionRequest) ProtoMessage()    {}
func (*TransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_action_90ba77703ae0bf49, []int{4}
}
func (m *TransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionRequest.Unmarshal(m, b)
}
func (m *TransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionRequest.Marshal(b, m, deterministic)
}
func (dst *TransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionRequest.Merge(dst, src)
}
func (m *TransactionRequest) XXX_Size() int {
	return xxx_messageInfo_TransactionRequest.Size(m)
}
func (m *TransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionRequest proto.InternalMessageInfo

func (m *TransactionRequest) GetReqID() string {
	if m != nil {
		return m.ReqID
	}
	return ""
}

func (m *TransactionRequest) GetContractAddr() string {
	if m != nil {
		return m.ContractAddr
	}
	return ""
}

func (m *TransactionRequest) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *TransactionRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *TransactionRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *TransactionRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *TransactionRequest) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

func (m *TransactionRequest) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *TransactionRequest) GetPrecision() uint32 {
	if m != nil {
		return m.Precision
	}
	return 0
}

type RawTransactionRequest struct {
	ReqID                string   `protobuf:"bytes,1,opt,name=reqID,proto3" json:"reqID,omitempty"`
	IsSigned             bool     `protobuf:"varint,2,opt,name=isSigned,proto3" json:"isSigned,omitempty"`
	Method               string   `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	ContractAddr         string   `protobuf:"bytes,4,opt,name=contractAddr,proto3" json:"contractAddr,omitempty"`
	Actor                string   `protobuf:"bytes,5,opt,name=actor,proto3" json:"actor,omitempty"`
	Params               string   `protobuf:"bytes,6,opt,name=params,proto3" json:"params,omitempty"`
	Permission           string   `protobuf:"bytes,7,opt,name=permission,proto3" json:"permission,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawTransactionRequest) Reset()         { *m = RawTransactionRequest{} }
func (m *RawTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*RawTransactionRequest) ProtoMessage()    {}
func (*RawTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_action_90ba77703ae0bf49, []int{5}
}
func (m *RawTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawTransactionRequest.Unmarshal(m, b)
}
func (m *RawTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawTransactionRequest.Marshal(b, m, deterministic)
}
func (dst *RawTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawTransactionRequest.Merge(dst, src)
}
func (m *RawTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_RawTransactionRequest.Size(m)
}
func (m *RawTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RawTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RawTransactionRequest proto.InternalMessageInfo

func (m *RawTransactionRequest) GetReqID() string {
	if m != nil {
		return m.ReqID
	}
	return ""
}

func (m *RawTransactionRequest) GetIsSigned() bool {
	if m != nil {
		return m.IsSigned
	}
	return false
}

func (m *RawTransactionRequest) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *RawTransactionRequest) GetContractAddr() string {
	if m != nil {
		return m.ContractAddr
	}
	return ""
}

func (m *RawTransactionRequest) GetActor() string {
	if m != nil {
		return m.Actor
	}
	return ""
}

func (m *RawTransactionRequest) GetParams() string {
	if m != nil {
		return m.Params
	}
	return ""
}

func (m *RawTransactionRequest) GetPermission() string {
	if m != nil {
		return m.Permission
	}
	return ""
}

type TransactionResponse struct {
	TransactionID        string   `protobuf:"bytes,1,opt,name=transactionID,proto3" json:"transactionID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionResponse) Reset()         { *m = TransactionResponse{} }
func (m *TransactionResponse) String() string { return proto.CompactTextString(m) }
func (*TransactionResponse) ProtoMessage()    {}
func (*TransactionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_action_90ba77703ae0bf49, []int{6}
}
func (m *TransactionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionResponse.Unmarshal(m, b)
}
func (m *TransactionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionResponse.Marshal(b, m, deterministic)
}
func (dst *TransactionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionResponse.Merge(dst, src)
}
func (m *TransactionResponse) XXX_Size() int {
	return xxx_messageInfo_TransactionResponse.Size(m)
}
func (m *TransactionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionResponse proto.InternalMessageInfo

func (m *TransactionResponse) GetTransactionID() string {
	if m != nil {
		return m.TransactionID
	}
	return ""
}

type GetTransactionInfoRequest struct {
	TransactionID        string   `protobuf:"bytes,1,opt,name=transactionID,proto3" json:"transactionID,omitempty"`
	Memo                 string   `protobuf:"bytes,2,opt,name=memo,proto3" json:"memo,omitempty"`
	To                   string   `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTransactionInfoRequest) Reset()         { *m = GetTransactionInfoRequest{} }
func (m *GetTransactionInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetTransactionInfoRequest) ProtoMessage()    {}
func (*GetTransactionInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_action_90ba77703ae0bf49, []int{7}
}
func (m *GetTransactionInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTransactionInfoRequest.Unmarshal(m, b)
}
func (m *GetTransactionInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTransactionInfoRequest.Marshal(b, m, deterministic)
}
func (dst *GetTransactionInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTransactionInfoRequest.Merge(dst, src)
}
func (m *GetTransactionInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetTransactionInfoRequest.Size(m)
}
func (m *GetTransactionInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTransactionInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTransactionInfoRequest proto.InternalMessageInfo

func (m *GetTransactionInfoRequest) GetTransactionID() string {
	if m != nil {
		return m.TransactionID
	}
	return ""
}

func (m *GetTransactionInfoRequest) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

func (m *GetTransactionInfoRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

type TransactionInfo struct {
	ConfirmTimes         int64             `protobuf:"varint,1,opt,name=confirmTimes,proto3" json:"confirmTimes,omitempty"`
	TransactionID        string            `protobuf:"bytes,2,opt,name=transactionID,proto3" json:"transactionID,omitempty"`
	BlockID              string            `protobuf:"bytes,3,opt,name=blockID,proto3" json:"blockID,omitempty"`
	BlockNumber          uint64            `protobuf:"varint,4,opt,name=blockNumber,proto3" json:"blockNumber,omitempty"`
	Data                 []*TransferRecord `protobuf:"bytes,5,rep,name=data,proto3" json:"data,omitempty"`
	Status               TransCode         `protobuf:"varint,6,opt,name=status,proto3,enum=action.TransCode" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *TransactionInfo) Reset()         { *m = TransactionInfo{} }
func (m *TransactionInfo) String() string { return proto.CompactTextString(m) }
func (*TransactionInfo) ProtoMessage()    {}
func (*TransactionInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_action_90ba77703ae0bf49, []int{8}
}
func (m *TransactionInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionInfo.Unmarshal(m, b)
}
func (m *TransactionInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionInfo.Marshal(b, m, deterministic)
}
func (dst *TransactionInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionInfo.Merge(dst, src)
}
func (m *TransactionInfo) XXX_Size() int {
	return xxx_messageInfo_TransactionInfo.Size(m)
}
func (m *TransactionInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionInfo proto.InternalMessageInfo

func (m *TransactionInfo) GetConfirmTimes() int64 {
	if m != nil {
		return m.ConfirmTimes
	}
	return 0
}

func (m *TransactionInfo) GetTransactionID() string {
	if m != nil {
		return m.TransactionID
	}
	return ""
}

func (m *TransactionInfo) GetBlockID() string {
	if m != nil {
		return m.BlockID
	}
	return ""
}

func (m *TransactionInfo) GetBlockNumber() uint64 {
	if m != nil {
		return m.BlockNumber
	}
	return 0
}

func (m *TransactionInfo) GetData() []*TransferRecord {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *TransactionInfo) GetStatus() TransCode {
	if m != nil {
		return m.Status
	}
	return TransCode_UNKNOW
}

type WatchTransferRequest struct {
	ContractAddr         string   `protobuf:"bytes,1,opt,name=contractAddr,proto3" json:"contractAddr,omitempty"`
	From                 string   `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Symbol               string   `protobuf:"bytes,4,opt,name=symbol,proto3" json:"symbol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WatchTransferRequest) Reset()         { *m = WatchTransferRequest{} }
func (m *WatchTransferRequest) String() string { return proto.CompactTextString(m) }
func (*WatchTransferRequest) ProtoMessage()    {}
func (*WatchTransferRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_action_90ba77703ae0bf49, []int{9}
}
func (m *WatchTransferRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WatchTransferRequest.Unmarshal(m, b)
}
func (m *WatchTransferRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WatchTransferRequest.Marshal(b, m, deterministic)
}
func (dst *WatchTransferRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WatchTransferRequest.Merge(dst, src)
}
func (m *WatchTransferRequest) XXX_Size() int {
	return xxx_messageInfo_WatchTransferRequest.Size(m)
}
func (m *WatchTransferRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WatchTransferRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WatchTransferRequest proto.InternalMessageInfo

func (m *WatchTransferRequest) GetContractAddr() string {
	if m != nil {
		return m.ContractAddr
	}
	return ""
}

func (m *WatchTransferRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *WatchTransferRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *WatchTransferRequest) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

type TransferRecord struct {
	From                 string   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Amount               string   `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Memo                 string   `protobuf:"bytes,4,opt,name=memo,proto3" json:"memo,omitempty"`
	Token                string   `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`
	ToAcctSeq            uint64   `protobuf:"varint,6,opt,name=toAcctSeq,proto3" json:"toAcctSeq,omitempty"`
	FromAcctSeq          uint64   `protobuf:"varint,7,opt,name=fromAcctSeq,proto3" json:"fromAcctSeq,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransferRecord) Reset()         { *m = TransferRecord{} }
func (m *TransferRecord) String() string { return proto.CompactTextString(m) }
func (*TransferRecord) ProtoMessage()    {}
func (*TransferRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_action_90ba77703ae0bf49, []int{10}
}
func (m *TransferRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransferRecord.Unmarshal(m, b)
}
func (m *TransferRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransferRecord.Marshal(b, m, deterministic)
}
func (dst *TransferRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferRecord.Merge(dst, src)
}
func (m *TransferRecord) XXX_Size() int {
	return xxx_messageInfo_TransferRecord.Size(m)
}
func (m *TransferRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferRecord.DiscardUnknown(m)
}

var xxx_messageInfo_TransferRecord proto.InternalMessageInfo

func (m *TransferRecord) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *TransferRecord) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *TransferRecord) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *TransferRecord) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

func (m *TransferRecord) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *TransferRecord) GetToAcctSeq() uint64 {
	if m != nil {
		return m.ToAcctSeq
	}
	return 0
}

func (m *TransferRecord) GetFromAcctSeq() uint64 {
	if m != nil {
		return m.FromAcctSeq
	}
	return 0
}

type GetTransferHistoryRequest struct {
	ContractAddr         string   `protobuf:"bytes,1,opt,name=contractAddr,proto3" json:"contractAddr,omitempty"`
	Start                uint64   `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	End                  uint64   `protobuf:"varint,3,opt,name=end,proto3" json:"end,omitempty"`
	From                 string   `protobuf:"bytes,4,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,5,opt,name=to,proto3" json:"to,omitempty"`
	Symbol               string   `protobuf:"bytes,6,opt,name=symbol,proto3" json:"symbol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTransferHistoryRequest) Reset()         { *m = GetTransferHistoryRequest{} }
func (m *GetTransferHistoryRequest) String() string { return proto.CompactTextString(m) }
func (*GetTransferHistoryRequest) ProtoMessage()    {}
func (*GetTransferHistoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_action_90ba77703ae0bf49, []int{11}
}
func (m *GetTransferHistoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTransferHistoryRequest.Unmarshal(m, b)
}
func (m *GetTransferHistoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTransferHistoryRequest.Marshal(b, m, deterministic)
}
func (dst *GetTransferHistoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTransferHistoryRequest.Merge(dst, src)
}
func (m *GetTransferHistoryRequest) XXX_Size() int {
	return xxx_messageInfo_GetTransferHistoryRequest.Size(m)
}
func (m *GetTransferHistoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTransferHistoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTransferHistoryRequest proto.InternalMessageInfo

func (m *GetTransferHistoryRequest) GetContractAddr() string {
	if m != nil {
		return m.ContractAddr
	}
	return ""
}

func (m *GetTransferHistoryRequest) GetStart() uint64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *GetTransferHistoryRequest) GetEnd() uint64 {
	if m != nil {
		return m.End
	}
	return 0
}

func (m *GetTransferHistoryRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *GetTransferHistoryRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *GetTransferHistoryRequest) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

type GetTransferHistoryResponse struct {
	Data                 []*TransactionInfo `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetTransferHistoryResponse) Reset()         { *m = GetTransferHistoryResponse{} }
func (m *GetTransferHistoryResponse) String() string { return proto.CompactTextString(m) }
func (*GetTransferHistoryResponse) ProtoMessage()    {}
func (*GetTransferHistoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_action_90ba77703ae0bf49, []int{12}
}
func (m *GetTransferHistoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTransferHistoryResponse.Unmarshal(m, b)
}
func (m *GetTransferHistoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTransferHistoryResponse.Marshal(b, m, deterministic)
}
func (dst *GetTransferHistoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTransferHistoryResponse.Merge(dst, src)
}
func (m *GetTransferHistoryResponse) XXX_Size() int {
	return xxx_messageInfo_GetTransferHistoryResponse.Size(m)
}
func (m *GetTransferHistoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTransferHistoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTransferHistoryResponse proto.InternalMessageInfo

func (m *GetTransferHistoryResponse) GetData() []*TransactionInfo {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetEOSActionsRequest struct {
	Account              string   `protobuf:"bytes,1,opt,name=Account,proto3" json:"Account,omitempty"`
	Start                uint64   `protobuf:"varint,2,opt,name=Start,proto3" json:"Start,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEOSActionsRequest) Reset()         { *m = GetEOSActionsRequest{} }
func (m *GetEOSActionsRequest) String() string { return proto.CompactTextString(m) }
func (*GetEOSActionsRequest) ProtoMessage()    {}
func (*GetEOSActionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_action_90ba77703ae0bf49, []int{13}
}
func (m *GetEOSActionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEOSActionsRequest.Unmarshal(m, b)
}
func (m *GetEOSActionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEOSActionsRequest.Marshal(b, m, deterministic)
}
func (dst *GetEOSActionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEOSActionsRequest.Merge(dst, src)
}
func (m *GetEOSActionsRequest) XXX_Size() int {
	return xxx_messageInfo_GetEOSActionsRequest.Size(m)
}
func (m *GetEOSActionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEOSActionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetEOSActionsRequest proto.InternalMessageInfo

func (m *GetEOSActionsRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *GetEOSActionsRequest) GetStart() uint64 {
	if m != nil {
		return m.Start
	}
	return 0
}

type GetEOSActionsResponse struct {
	Data                 []*EOSAction `protobuf:"bytes,1,rep,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetEOSActionsResponse) Reset()         { *m = GetEOSActionsResponse{} }
func (m *GetEOSActionsResponse) String() string { return proto.CompactTextString(m) }
func (*GetEOSActionsResponse) ProtoMessage()    {}
func (*GetEOSActionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_action_90ba77703ae0bf49, []int{14}
}
func (m *GetEOSActionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEOSActionsResponse.Unmarshal(m, b)
}
func (m *GetEOSActionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEOSActionsResponse.Marshal(b, m, deterministic)
}
func (dst *GetEOSActionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEOSActionsResponse.Merge(dst, src)
}
func (m *GetEOSActionsResponse) XXX_Size() int {
	return xxx_messageInfo_GetEOSActionsResponse.Size(m)
}
func (m *GetEOSActionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEOSActionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetEOSActionsResponse proto.InternalMessageInfo

func (m *GetEOSActionsResponse) GetData() []*EOSAction {
	if m != nil {
		return m.Data
	}
	return nil
}

type EOSAction struct {
	ContractAddr         string   `protobuf:"bytes,1,opt,name=ContractAddr,proto3" json:"ContractAddr,omitempty"`
	Action               string   `protobuf:"bytes,2,opt,name=Action,proto3" json:"Action,omitempty"`
	AccountSeq           uint64   `protobuf:"varint,3,opt,name=AccountSeq,proto3" json:"AccountSeq,omitempty"`
	BlockNum             uint64   `protobuf:"varint,4,opt,name=BlockNum,proto3" json:"BlockNum,omitempty"`
	From                 string   `protobuf:"bytes,5,opt,name=From,proto3" json:"From,omitempty"`
	To                   string   `protobuf:"bytes,6,opt,name=To,proto3" json:"To,omitempty"`
	Amount               uint64   `protobuf:"varint,7,opt,name=Amount,proto3" json:"Amount,omitempty"`
	Symbol               string   `protobuf:"bytes,8,opt,name=Symbol,proto3" json:"Symbol,omitempty"`
	Memo                 string   `protobuf:"bytes,9,opt,name=Memo,proto3" json:"Memo,omitempty"`
	Time                 uint64   `protobuf:"varint,10,opt,name=Time,proto3" json:"Time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EOSAction) Reset()         { *m = EOSAction{} }
func (m *EOSAction) String() string { return proto.CompactTextString(m) }
func (*EOSAction) ProtoMessage()    {}
func (*EOSAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_action_90ba77703ae0bf49, []int{15}
}
func (m *EOSAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EOSAction.Unmarshal(m, b)
}
func (m *EOSAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EOSAction.Marshal(b, m, deterministic)
}
func (dst *EOSAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EOSAction.Merge(dst, src)
}
func (m *EOSAction) XXX_Size() int {
	return xxx_messageInfo_EOSAction.Size(m)
}
func (m *EOSAction) XXX_DiscardUnknown() {
	xxx_messageInfo_EOSAction.DiscardUnknown(m)
}

var xxx_messageInfo_EOSAction proto.InternalMessageInfo

func (m *EOSAction) GetContractAddr() string {
	if m != nil {
		return m.ContractAddr
	}
	return ""
}

func (m *EOSAction) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *EOSAction) GetAccountSeq() uint64 {
	if m != nil {
		return m.AccountSeq
	}
	return 0
}

func (m *EOSAction) GetBlockNum() uint64 {
	if m != nil {
		return m.BlockNum
	}
	return 0
}

func (m *EOSAction) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *EOSAction) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *EOSAction) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *EOSAction) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *EOSAction) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

func (m *EOSAction) GetTime() uint64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type CheckAccountRequest struct {
	Account              string   `protobuf:"bytes,1,opt,name=Account,proto3" json:"Account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckAccountRequest) Reset()         { *m = CheckAccountRequest{} }
func (m *CheckAccountRequest) String() string { return proto.CompactTextString(m) }
func (*CheckAccountRequest) ProtoMessage()    {}
func (*CheckAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_action_90ba77703ae0bf49, []int{16}
}
func (m *CheckAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckAccountRequest.Unmarshal(m, b)
}
func (m *CheckAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckAccountRequest.Marshal(b, m, deterministic)
}
func (dst *CheckAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckAccountRequest.Merge(dst, src)
}
func (m *CheckAccountRequest) XXX_Size() int {
	return xxx_messageInfo_CheckAccountRequest.Size(m)
}
func (m *CheckAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckAccountRequest proto.InternalMessageInfo

func (m *CheckAccountRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

type CheckAccountResponse struct {
	Account              string   `protobuf:"bytes,1,opt,name=Account,proto3" json:"Account,omitempty"`
	IsExist              bool     `protobuf:"varint,2,opt,name=IsExist,proto3" json:"IsExist,omitempty"`
	Err                  string   `protobuf:"bytes,3,opt,name=Err,proto3" json:"Err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckAccountResponse) Reset()         { *m = CheckAccountResponse{} }
func (m *CheckAccountResponse) String() string { return proto.CompactTextString(m) }
func (*CheckAccountResponse) ProtoMessage()    {}
func (*CheckAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_action_90ba77703ae0bf49, []int{17}
}
func (m *CheckAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckAccountResponse.Unmarshal(m, b)
}
func (m *CheckAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckAccountResponse.Marshal(b, m, deterministic)
}
func (dst *CheckAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckAccountResponse.Merge(dst, src)
}
func (m *CheckAccountResponse) XXX_Size() int {
	return xxx_messageInfo_CheckAccountResponse.Size(m)
}
func (m *CheckAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckAccountResponse proto.InternalMessageInfo

func (m *CheckAccountResponse) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *CheckAccountResponse) GetIsExist() bool {
	if m != nil {
		return m.IsExist
	}
	return false
}

func (m *CheckAccountResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type GetCurrencyStatsRequest struct {
	Account              string   `protobuf:"bytes,1,opt,name=Account,proto3" json:"Account,omitempty"`
	Symbol               string   `protobuf:"bytes,2,opt,name=Symbol,proto3" json:"Symbol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCurrencyStatsRequest) Reset()         { *m = GetCurrencyStatsRequest{} }
func (m *GetCurrencyStatsRequest) String() string { return proto.CompactTextString(m) }
func (*GetCurrencyStatsRequest) ProtoMessage()    {}
func (*GetCurrencyStatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_action_90ba77703ae0bf49, []int{18}
}
func (m *GetCurrencyStatsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCurrencyStatsRequest.Unmarshal(m, b)
}
func (m *GetCurrencyStatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCurrencyStatsRequest.Marshal(b, m, deterministic)
}
func (dst *GetCurrencyStatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCurrencyStatsRequest.Merge(dst, src)
}
func (m *GetCurrencyStatsRequest) XXX_Size() int {
	return xxx_messageInfo_GetCurrencyStatsRequest.Size(m)
}
func (m *GetCurrencyStatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCurrencyStatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCurrencyStatsRequest proto.InternalMessageInfo

func (m *GetCurrencyStatsRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *GetCurrencyStatsRequest) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

type GetCurrencyStatsResponse struct {
	Supply               uint64   `protobuf:"varint,1,opt,name=Supply,proto3" json:"Supply,omitempty"`
	Symbol               string   `protobuf:"bytes,2,opt,name=Symbol,proto3" json:"Symbol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCurrencyStatsResponse) Reset()         { *m = GetCurrencyStatsResponse{} }
func (m *GetCurrencyStatsResponse) String() string { return proto.CompactTextString(m) }
func (*GetCurrencyStatsResponse) ProtoMessage()    {}
func (*GetCurrencyStatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_action_90ba77703ae0bf49, []int{19}
}
func (m *GetCurrencyStatsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCurrencyStatsResponse.Unmarshal(m, b)
}
func (m *GetCurrencyStatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCurrencyStatsResponse.Marshal(b, m, deterministic)
}
func (dst *GetCurrencyStatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCurrencyStatsResponse.Merge(dst, src)
}
func (m *GetCurrencyStatsResponse) XXX_Size() int {
	return xxx_messageInfo_GetCurrencyStatsResponse.Size(m)
}
func (m *GetCurrencyStatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCurrencyStatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCurrencyStatsResponse proto.InternalMessageInfo

func (m *GetCurrencyStatsResponse) GetSupply() uint64 {
	if m != nil {
		return m.Supply
	}
	return 0
}

func (m *GetCurrencyStatsResponse) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func init() {
	proto.RegisterType((*AccountRequest)(nil), "action.AccountRequest")
	proto.RegisterType((*AccountResponse)(nil), "action.AccountResponse")
	proto.RegisterType((*GetBalanceRequest)(nil), "action.GetBalanceRequest")
	proto.RegisterType((*GetBalanceResponse)(nil), "action.GetBalanceResponse")
	proto.RegisterType((*TransactionRequest)(nil), "action.TransactionRequest")
	proto.RegisterType((*RawTransactionRequest)(nil), "action.RawTransactionRequest")
	proto.RegisterType((*TransactionResponse)(nil), "action.TransactionResponse")
	proto.RegisterType((*GetTransactionInfoRequest)(nil), "action.GetTransactionInfoRequest")
	proto.RegisterType((*TransactionInfo)(nil), "action.TransactionInfo")
	proto.RegisterType((*WatchTransferRequest)(nil), "action.WatchTransferRequest")
	proto.RegisterType((*TransferRecord)(nil), "action.TransferRecord")
	proto.RegisterType((*GetTransferHistoryRequest)(nil), "action.GetTransferHistoryRequest")
	proto.RegisterType((*GetTransferHistoryResponse)(nil), "action.GetTransferHistoryResponse")
	proto.RegisterType((*GetEOSActionsRequest)(nil), "action.GetEOSActionsRequest")
	proto.RegisterType((*GetEOSActionsResponse)(nil), "action.GetEOSActionsResponse")
	proto.RegisterType((*EOSAction)(nil), "action.EOSAction")
	proto.RegisterType((*CheckAccountRequest)(nil), "action.CheckAccountRequest")
	proto.RegisterType((*CheckAccountResponse)(nil), "action.CheckAccountResponse")
	proto.RegisterType((*GetCurrencyStatsRequest)(nil), "action.GetCurrencyStatsRequest")
	proto.RegisterType((*GetCurrencyStatsResponse)(nil), "action.GetCurrencyStatsResponse")
	proto.RegisterEnum("action.RespCode", RespCode_name, RespCode_value)
	proto.RegisterEnum("action.TransCode", TransCode_name, TransCode_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ActionServiceClient is the client API for ActionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ActionServiceClient interface {
	NewAccount(ctx context.Context, in *AccountRequest, opts ...grpc.CallOption) (*AccountResponse, error)
	CheckAccount(ctx context.Context, in *CheckAccountRequest, opts ...grpc.CallOption) (*CheckAccountResponse, error)
	GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error)
	Issue(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*TransactionResponse, error)
	Burn(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*TransactionResponse, error)
	GetTransactionInfo(ctx context.Context, in *GetTransactionInfoRequest, opts ...grpc.CallOption) (*TransactionInfo, error)
	WatchTransfer(ctx context.Context, opts ...grpc.CallOption) (ActionService_WatchTransferClient, error)
	GetTransferHistory(ctx context.Context, in *GetTransferHistoryRequest, opts ...grpc.CallOption) (*GetTransferHistoryResponse, error)
	Transfer(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*TransactionResponse, error)
	RawTx(ctx context.Context, in *RawTransactionRequest, opts ...grpc.CallOption) (*TransactionResponse, error)
	GetEOSActions(ctx context.Context, in *GetEOSActionsRequest, opts ...grpc.CallOption) (*GetEOSActionsResponse, error)
	GetCurrencyStats(ctx context.Context, in *GetCurrencyStatsRequest, opts ...grpc.CallOption) (*GetCurrencyStatsResponse, error)
}

type actionServiceClient struct {
	cc *grpc.ClientConn
}

func NewActionServiceClient(cc *grpc.ClientConn) ActionServiceClient {
	return &actionServiceClient{cc}
}

func (c *actionServiceClient) NewAccount(ctx context.Context, in *AccountRequest, opts ...grpc.CallOption) (*AccountResponse, error) {
	out := new(AccountResponse)
	err := c.cc.Invoke(ctx, "/action.ActionService/NewAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *actionServiceClient) CheckAccount(ctx context.Context, in *CheckAccountRequest, opts ...grpc.CallOption) (*CheckAccountResponse, error) {
	out := new(CheckAccountResponse)
	err := c.cc.Invoke(ctx, "/action.ActionService/CheckAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *actionServiceClient) GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error) {
	out := new(GetBalanceResponse)
	err := c.cc.Invoke(ctx, "/action.ActionService/GetBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *actionServiceClient) Issue(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*TransactionResponse, error) {
	out := new(TransactionResponse)
	err := c.cc.Invoke(ctx, "/action.ActionService/Issue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *actionServiceClient) Burn(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*TransactionResponse, error) {
	out := new(TransactionResponse)
	err := c.cc.Invoke(ctx, "/action.ActionService/Burn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *actionServiceClient) GetTransactionInfo(ctx context.Context, in *GetTransactionInfoRequest, opts ...grpc.CallOption) (*TransactionInfo, error) {
	out := new(TransactionInfo)
	err := c.cc.Invoke(ctx, "/action.ActionService/GetTransactionInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *actionServiceClient) WatchTransfer(ctx context.Context, opts ...grpc.CallOption) (ActionService_WatchTransferClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ActionService_serviceDesc.Streams[0], "/action.ActionService/WatchTransfer", opts...)
	if err != nil {
		return nil, err
	}
	x := &actionServiceWatchTransferClient{stream}
	return x, nil
}

type ActionService_WatchTransferClient interface {
	Send(*WatchTransferRequest) error
	Recv() (*TransactionInfo, error)
	grpc.ClientStream
}

type actionServiceWatchTransferClient struct {
	grpc.ClientStream
}

func (x *actionServiceWatchTransferClient) Send(m *WatchTransferRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *actionServiceWatchTransferClient) Recv() (*TransactionInfo, error) {
	m := new(TransactionInfo)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *actionServiceClient) GetTransferHistory(ctx context.Context, in *GetTransferHistoryRequest, opts ...grpc.CallOption) (*GetTransferHistoryResponse, error) {
	out := new(GetTransferHistoryResponse)
	err := c.cc.Invoke(ctx, "/action.ActionService/GetTransferHistory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *actionServiceClient) Transfer(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*TransactionResponse, error) {
	out := new(TransactionResponse)
	err := c.cc.Invoke(ctx, "/action.ActionService/Transfer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *actionServiceClient) RawTx(ctx context.Context, in *RawTransactionRequest, opts ...grpc.CallOption) (*TransactionResponse, error) {
	out := new(TransactionResponse)
	err := c.cc.Invoke(ctx, "/action.ActionService/RawTx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *actionServiceClient) GetEOSActions(ctx context.Context, in *GetEOSActionsRequest, opts ...grpc.CallOption) (*GetEOSActionsResponse, error) {
	out := new(GetEOSActionsResponse)
	err := c.cc.Invoke(ctx, "/action.ActionService/GetEOSActions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *actionServiceClient) GetCurrencyStats(ctx context.Context, in *GetCurrencyStatsRequest, opts ...grpc.CallOption) (*GetCurrencyStatsResponse, error) {
	out := new(GetCurrencyStatsResponse)
	err := c.cc.Invoke(ctx, "/action.ActionService/GetCurrencyStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ActionServiceServer is the server API for ActionService service.
type ActionServiceServer interface {
	NewAccount(context.Context, *AccountRequest) (*AccountResponse, error)
	CheckAccount(context.Context, *CheckAccountRequest) (*CheckAccountResponse, error)
	GetBalance(context.Context, *GetBalanceRequest) (*GetBalanceResponse, error)
	Issue(context.Context, *TransactionRequest) (*TransactionResponse, error)
	Burn(context.Context, *TransactionRequest) (*TransactionResponse, error)
	GetTransactionInfo(context.Context, *GetTransactionInfoRequest) (*TransactionInfo, error)
	WatchTransfer(ActionService_WatchTransferServer) error
	GetTransferHistory(context.Context, *GetTransferHistoryRequest) (*GetTransferHistoryResponse, error)
	Transfer(context.Context, *TransactionRequest) (*TransactionResponse, error)
	RawTx(context.Context, *RawTransactionRequest) (*TransactionResponse, error)
	GetEOSActions(context.Context, *GetEOSActionsRequest) (*GetEOSActionsResponse, error)
	GetCurrencyStats(context.Context, *GetCurrencyStatsRequest) (*GetCurrencyStatsResponse, error)
}

func RegisterActionServiceServer(s *grpc.Server, srv ActionServiceServer) {
	s.RegisterService(&_ActionService_serviceDesc, srv)
}

func _ActionService_NewAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActionServiceServer).NewAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/action.ActionService/NewAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActionServiceServer).NewAccount(ctx, req.(*AccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActionService_CheckAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActionServiceServer).CheckAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/action.ActionService/CheckAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActionServiceServer).CheckAccount(ctx, req.(*CheckAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActionService_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActionServiceServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/action.ActionService/GetBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActionServiceServer).GetBalance(ctx, req.(*GetBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActionService_Issue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActionServiceServer).Issue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/action.ActionService/Issue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActionServiceServer).Issue(ctx, req.(*TransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActionService_Burn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActionServiceServer).Burn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/action.ActionService/Burn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActionServiceServer).Burn(ctx, req.(*TransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActionService_GetTransactionInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActionServiceServer).GetTransactionInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/action.ActionService/GetTransactionInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActionServiceServer).GetTransactionInfo(ctx, req.(*GetTransactionInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActionService_WatchTransfer_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ActionServiceServer).WatchTransfer(&actionServiceWatchTransferServer{stream})
}

type ActionService_WatchTransferServer interface {
	Send(*TransactionInfo) error
	Recv() (*WatchTransferRequest, error)
	grpc.ServerStream
}

type actionServiceWatchTransferServer struct {
	grpc.ServerStream
}

func (x *actionServiceWatchTransferServer) Send(m *TransactionInfo) error {
	return x.ServerStream.SendMsg(m)
}

func (x *actionServiceWatchTransferServer) Recv() (*WatchTransferRequest, error) {
	m := new(WatchTransferRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ActionService_GetTransferHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransferHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActionServiceServer).GetTransferHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/action.ActionService/GetTransferHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActionServiceServer).GetTransferHistory(ctx, req.(*GetTransferHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActionService_Transfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActionServiceServer).Transfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/action.ActionService/Transfer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActionServiceServer).Transfer(ctx, req.(*TransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActionService_RawTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RawTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActionServiceServer).RawTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/action.ActionService/RawTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActionServiceServer).RawTx(ctx, req.(*RawTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActionService_GetEOSActions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEOSActionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActionServiceServer).GetEOSActions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/action.ActionService/GetEOSActions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActionServiceServer).GetEOSActions(ctx, req.(*GetEOSActionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActionService_GetCurrencyStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurrencyStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActionServiceServer).GetCurrencyStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/action.ActionService/GetCurrencyStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActionServiceServer).GetCurrencyStats(ctx, req.(*GetCurrencyStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ActionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "action.ActionService",
	HandlerType: (*ActionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewAccount",
			Handler:    _ActionService_NewAccount_Handler,
		},
		{
			MethodName: "CheckAccount",
			Handler:    _ActionService_CheckAccount_Handler,
		},
		{
			MethodName: "GetBalance",
			Handler:    _ActionService_GetBalance_Handler,
		},
		{
			MethodName: "Issue",
			Handler:    _ActionService_Issue_Handler,
		},
		{
			MethodName: "Burn",
			Handler:    _ActionService_Burn_Handler,
		},
		{
			MethodName: "GetTransactionInfo",
			Handler:    _ActionService_GetTransactionInfo_Handler,
		},
		{
			MethodName: "GetTransferHistory",
			Handler:    _ActionService_GetTransferHistory_Handler,
		},
		{
			MethodName: "Transfer",
			Handler:    _ActionService_Transfer_Handler,
		},
		{
			MethodName: "RawTx",
			Handler:    _ActionService_RawTx_Handler,
		},
		{
			MethodName: "GetEOSActions",
			Handler:    _ActionService_GetEOSActions_Handler,
		},
		{
			MethodName: "GetCurrencyStats",
			Handler:    _ActionService_GetCurrencyStats_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchTransfer",
			Handler:       _ActionService_WatchTransfer_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "action/action.proto",
}

func init() { proto.RegisterFile("action/action.proto", fileDescriptor_action_90ba77703ae0bf49) }

var fileDescriptor_action_90ba77703ae0bf49 = []byte{
	// 1232 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x57, 0xeb, 0x72, 0xd3, 0xc6,
	0x17, 0x8f, 0x6c, 0xf9, 0x76, 0xc0, 0xc1, 0x6c, 0x4c, 0x22, 0x04, 0xfc, 0xff, 0xa9, 0xa6, 0x4c,
	0x29, 0x74, 0x92, 0x0e, 0xfd, 0xc8, 0x4c, 0x3b, 0x8e, 0x6d, 0x82, 0x1b, 0x6a, 0x53, 0xd9, 0x2d,
	0x33, 0x9d, 0x76, 0x18, 0x45, 0xda, 0x10, 0x0d, 0x96, 0xd6, 0xac, 0xd6, 0x84, 0x3c, 0x0f, 0xef,
	0xd0, 0x17, 0xe9, 0x7b, 0x74, 0xfa, 0x06, 0xed, 0xec, 0x4d, 0x17, 0x5b, 0xa6, 0xe9, 0xf0, 0xc9,
	0x7b, 0xce, 0x9e, 0xfd, 0xe9, 0x9c, 0xdf, 0xb9, 0xec, 0x1a, 0x76, 0x3c, 0x9f, 0x85, 0x24, 0x3e,
	0x94, 0x3f, 0x07, 0x0b, 0x4a, 0x18, 0x41, 0x75, 0x29, 0x39, 0x5f, 0xc1, 0x76, 0xcf, 0xf7, 0xc9,
	0x32, 0x66, 0x2e, 0x7e, 0xbb, 0xc4, 0x09, 0x43, 0x36, 0x34, 0x17, 0x5e, 0x92, 0x5c, 0x10, 0x1a,
	0x58, 0xc6, 0xbe, 0xf1, 0xa0, 0xe5, 0xa6, 0xb2, 0xf3, 0x08, 0x6e, 0xa4, 0xd6, 0xc9, 0x82, 0xc4,
	0x09, 0x46, 0x16, 0x34, 0xbc, 0x20, 0xa0, 0x38, 0x49, 0x94, 0xb5, 0x16, 0x9d, 0x10, 0x6e, 0x1e,
	0x63, 0x76, 0xe4, 0xcd, 0xbd, 0xd8, 0xc7, 0x1a, 0xdd, 0x81, 0xeb, 0x3e, 0x89, 0x19, 0xf5, 0x7c,
	0xd6, 0x0b, 0x02, 0xaa, 0xce, 0x14, 0x74, 0x79, 0xc8, 0x4a, 0x01, 0x12, 0xed, 0x42, 0x3d, 0xb9,
	0x8c, 0x4e, 0xc9, 0xdc, 0xaa, 0x8a, 0x0d, 0x25, 0x39, 0xcf, 0x00, 0xe5, 0x3f, 0x95, 0xb9, 0x76,
	0x2a, 0x55, 0xda, 0x35, 0x25, 0xf2, 0x9d, 0x00, 0xfb, 0x61, 0xe4, 0xcd, 0xc5, 0x17, 0xda, 0xae,
	0x16, 0x9d, 0xbf, 0x0c, 0x40, 0x33, 0xea, 0xc5, 0x89, 0xe4, 0x47, 0xbb, 0xdd, 0x85, 0x1a, 0xc5,
	0x6f, 0x47, 0x03, 0x05, 0x24, 0x85, 0xb5, 0x60, 0x2a, 0x25, 0xc1, 0xec, 0x42, 0xdd, 0x8b, 0x38,
	0x63, 0xda, 0x65, 0x29, 0x15, 0x68, 0x36, 0x8b, 0x34, 0x23, 0x04, 0xe6, 0x19, 0x25, 0x91, 0x55,
	0x13, 0x7a, 0xb1, 0x46, 0xdb, 0x50, 0x61, 0xc4, 0xaa, 0x0b, 0x4d, 0x85, 0x11, 0x6e, 0x13, 0xe1,
	0x88, 0x58, 0x0d, 0x69, 0xc3, 0xd7, 0x39, 0x7a, 0x9a, 0x79, 0x7a, 0xd0, 0x5d, 0x68, 0x2d, 0x28,
	0xf6, 0xc3, 0x24, 0x24, 0xb1, 0xd5, 0x12, 0x01, 0x67, 0x0a, 0xe7, 0x0f, 0x03, 0x6e, 0xb9, 0xde,
	0xc5, 0x95, 0xa3, 0xb6, 0xa1, 0x19, 0x26, 0xd3, 0xf0, 0x75, 0x8c, 0x03, 0x11, 0x71, 0xd3, 0x4d,
	0x65, 0xee, 0x41, 0x84, 0xd9, 0x39, 0x09, 0x74, 0xb4, 0x52, 0x5a, 0x63, 0xca, 0x2c, 0x61, 0xaa,
	0x0b, 0x35, 0xcf, 0x67, 0x84, 0xaa, 0xb0, 0xa5, 0xc0, 0x11, 0x17, 0x1e, 0xf5, 0xa2, 0x44, 0xc5,
	0xae, 0x24, 0xf4, 0x3f, 0x80, 0x05, 0xa6, 0x51, 0x98, 0x88, 0xa0, 0x24, 0x0b, 0x39, 0x8d, 0xf3,
	0x04, 0x76, 0x0a, 0x11, 0xa9, 0x9a, 0xf8, 0x1c, 0xda, 0x2c, 0x53, 0xa7, 0xa1, 0x15, 0x95, 0x0e,
	0x86, 0xdb, 0xc7, 0x98, 0xe5, 0xce, 0x8f, 0xe2, 0x33, 0xa2, 0x59, 0xb9, 0x12, 0x44, 0x9a, 0x9f,
	0x4a, 0x2e, 0x3f, 0x32, 0x87, 0x55, 0x9d, 0x43, 0xe7, 0x4f, 0x03, 0x6e, 0xac, 0x7c, 0x44, 0x31,
	0x75, 0x16, 0xd2, 0x68, 0x16, 0x46, 0x58, 0x36, 0x55, 0xd5, 0x2d, 0xe8, 0xd6, 0x3d, 0xa8, 0x94,
	0x79, 0xc0, 0xcb, 0x7f, 0x4e, 0xfc, 0x37, 0xa3, 0x81, 0xfa, 0xa4, 0x16, 0xd1, 0x3e, 0x5c, 0x13,
	0xcb, 0xf1, 0x32, 0x3a, 0xc5, 0x32, 0x19, 0xa6, 0x9b, 0x57, 0xa1, 0x87, 0x60, 0x06, 0x1e, 0xf3,
	0xac, 0xda, 0x7e, 0xf5, 0xc1, 0xb5, 0xc7, 0xbb, 0x07, 0x6a, 0x76, 0x08, 0x67, 0xcf, 0x30, 0x75,
	0xb1, 0x4f, 0x68, 0xe0, 0x0a, 0x1b, 0xf4, 0x25, 0xd4, 0x13, 0xe6, 0xb1, 0xa5, 0xcc, 0xd0, 0xf6,
	0xe3, 0x9b, 0x05, 0xeb, 0x3e, 0x09, 0xb0, 0xab, 0x0c, 0x9c, 0x77, 0xd0, 0x7d, 0xe9, 0x31, 0xff,
	0x3c, 0xc3, 0xb9, 0xfa, 0x54, 0xd0, 0x4d, 0x51, 0x59, 0x6b, 0x8a, 0x94, 0xd0, 0x5c, 0x03, 0x98,
	0x85, 0xf9, 0xf0, 0xbb, 0x01, 0xdb, 0x45, 0xdf, 0x53, 0x38, 0x63, 0x0d, 0xae, 0x92, 0x87, 0x2b,
	0xed, 0x5d, 0x9d, 0x5b, 0x33, 0x97, 0xdb, 0x2e, 0xd4, 0x18, 0x79, 0x83, 0x63, 0x5d, 0xbd, 0x42,
	0xe0, 0x9d, 0xc7, 0x48, 0xcf, 0xf7, 0xd9, 0x14, 0xbf, 0x15, 0xf4, 0x98, 0x6e, 0xa6, 0xe0, 0x79,
	0xe0, 0xdf, 0xd5, 0xfb, 0x0d, 0x99, 0x87, 0x9c, 0xca, 0xf9, 0x60, 0x64, 0x95, 0x78, 0x86, 0xe9,
	0xb3, 0x30, 0x61, 0x84, 0x5e, 0xfe, 0x17, 0xda, 0xba, 0x50, 0x4b, 0x98, 0x47, 0x99, 0x08, 0xcb,
	0x74, 0xa5, 0x80, 0x3a, 0x50, 0xc5, 0xb1, 0x6c, 0x52, 0xd3, 0xe5, 0xcb, 0x94, 0x0f, 0x73, 0x8d,
	0x8f, 0x5a, 0x09, 0xbd, 0xf5, 0x02, 0xbd, 0x23, 0xb0, 0xcb, 0x9c, 0x54, 0x2d, 0xf7, 0x48, 0xd5,
	0x92, 0x21, 0x6a, 0x69, 0xaf, 0x50, 0x1d, 0xb9, 0xee, 0x12, 0x46, 0xce, 0x53, 0xe8, 0x1e, 0x63,
	0x36, 0x9c, 0x4c, 0x7b, 0x62, 0x27, 0xd1, 0xa1, 0x5a, 0xd0, 0x50, 0x37, 0x8f, 0x9e, 0xe5, 0x4a,
	0xe4, 0x01, 0x4e, 0xf3, 0x01, 0x0a, 0xc1, 0xf9, 0x16, 0x6e, 0xad, 0xe0, 0x28, 0x6f, 0xee, 0x83,
	0x39, 0xc8, 0xbc, 0x49, 0x6b, 0x35, 0xb5, 0x74, 0xc5, 0xb6, 0xf3, 0xb7, 0x01, 0xad, 0x54, 0xc7,
	0x89, 0xee, 0x97, 0x10, 0xdd, 0x5f, 0x19, 0xf4, 0xd2, 0x5a, 0x15, 0x90, 0x92, 0xf8, 0xa0, 0x52,
	0xae, 0xf2, 0x1c, 0x4b, 0xc6, 0x73, 0x1a, 0x3e, 0x4e, 0x8f, 0x54, 0xe7, 0xa9, 0x4e, 0x4c, 0x65,
	0x9e, 0x94, 0xa7, 0xb9, 0x8b, 0xe0, 0xa9, 0x4a, 0xca, 0x2c, 0xbd, 0x08, 0x66, 0x22, 0x29, 0x3d,
	0x59, 0xa4, 0xb2, 0x7e, 0x94, 0xc4, 0xf5, 0xd3, 0xc2, 0x65, 0x20, 0x25, 0x8e, 0xf9, 0x03, 0x2f,
	0xde, 0x96, 0xc4, 0xe4, 0x6b, 0xae, 0xe3, 0x93, 0xc5, 0x02, 0x81, 0x20, 0xd6, 0xce, 0x21, 0xec,
	0xf4, 0xcf, 0xb1, 0xff, 0x66, 0xe5, 0x79, 0xb0, 0x31, 0x11, 0xce, 0xaf, 0xd0, 0x2d, 0x1e, 0xc8,
	0xae, 0xe1, 0x0d, 0xa9, 0xb3, 0xa0, 0x31, 0x4a, 0x86, 0xef, 0xc3, 0x84, 0xa9, 0x8b, 0x44, 0x8b,
	0xbc, 0x3e, 0x87, 0x94, 0xaa, 0xb6, 0xe3, 0x4b, 0xe7, 0x04, 0xf6, 0x8e, 0x31, 0xeb, 0x2f, 0x29,
	0xc5, 0xb1, 0x7f, 0x39, 0x65, 0x1e, 0xbb, 0x42, 0x6d, 0x64, 0x1c, 0x54, 0xf2, 0x1c, 0x38, 0xdf,
	0x83, 0xb5, 0x0e, 0xa6, 0xdc, 0xe5, 0x67, 0x96, 0x8b, 0xc5, 0xfc, 0x52, 0x80, 0x99, 0xae, 0x92,
	0x36, 0x61, 0x3d, 0x9c, 0x42, 0x93, 0x9f, 0xe5, 0x73, 0x0e, 0xd5, 0xa1, 0x32, 0x39, 0xe9, 0x6c,
	0xa1, 0x1d, 0xb8, 0x31, 0x1a, 0xff, 0xdc, 0x7b, 0x3e, 0x1a, 0xbc, 0xea, 0x0d, 0x06, 0xee, 0x70,
	0x3a, 0xed, 0xdc, 0x42, 0x37, 0xa1, 0xad, 0x95, 0xee, 0xf0, 0xc7, 0xd1, 0xa0, 0xb3, 0x8b, 0xf6,
	0x60, 0x67, 0xe6, 0xf6, 0xc6, 0xd3, 0x5e, 0x7f, 0x36, 0x9a, 0x8c, 0x5f, 0x3d, 0xeb, 0x8d, 0x07,
	0xa3, 0xf1, 0x71, 0x67, 0xef, 0xe1, 0x13, 0x68, 0xa5, 0xd3, 0x13, 0x01, 0xd4, 0x7f, 0x1a, 0x9f,
	0x8c, 0x27, 0x2f, 0x3b, 0x5b, 0xe8, 0x1a, 0x34, 0x5e, 0x0c, 0xa5, 0x95, 0x81, 0x9a, 0x60, 0x0e,
	0x26, 0xe3, 0x61, 0xa7, 0xc2, 0xd5, 0x03, 0x77, 0xf2, 0xe2, 0xc5, 0x70, 0xd0, 0xa9, 0x3e, 0xfe,
	0xd0, 0x80, 0xb6, 0x2c, 0xbe, 0x29, 0xa6, 0xef, 0x42, 0x1f, 0xa3, 0xef, 0x00, 0xc6, 0xf8, 0x22,
	0x65, 0x45, 0x17, 0x7d, 0x31, 0xb5, 0xf6, 0xde, 0x9a, 0x5e, 0x52, 0xe2, 0x6c, 0xa1, 0x13, 0xb8,
	0x9e, 0xcf, 0x2d, 0xba, 0xa3, 0x4d, 0x4b, 0x4a, 0xc4, 0xbe, 0x5b, 0xbe, 0x99, 0x82, 0x0d, 0x01,
	0xb2, 0xd7, 0x1a, 0xba, 0xad, 0xad, 0xd7, 0x1e, 0x8b, 0xb6, 0x5d, 0xb6, 0x95, 0xc2, 0x1c, 0x41,
	0x6d, 0x94, 0x24, 0x4b, 0x8c, 0xec, 0x92, 0x91, 0xa2, 0x21, 0xee, 0x94, 0xee, 0xa5, 0x18, 0x3d,
	0x30, 0x8f, 0x96, 0x34, 0xfe, 0x14, 0x08, 0x57, 0xbc, 0x3d, 0x57, 0xaf, 0xf1, 0xcf, 0x72, 0xae,
	0x97, 0xbf, 0x23, 0xec, 0x4d, 0x93, 0xd0, 0xd9, 0x42, 0xcf, 0xa1, 0x5d, 0xb8, 0x27, 0x51, 0x4a,
	0x69, 0xd9, 0xf5, 0xf9, 0x11, 0xa4, 0x07, 0xc6, 0xd7, 0x06, 0xfa, 0x2d, 0xf3, 0x30, 0x1b, 0xcf,
	0xeb, 0x1e, 0xae, 0xdd, 0x2f, 0xb6, 0xf3, 0x31, 0x93, 0x5c, 0x3a, 0x9b, 0xa9, 0x9f, 0x9f, 0xc0,
	0xe3, 0x10, 0x6a, 0xfc, 0x15, 0xfa, 0x1e, 0xdd, 0xd3, 0x76, 0xa5, 0x8f, 0xd2, 0x7f, 0x83, 0x19,
	0x43, 0xbb, 0x30, 0xf8, 0x33, 0xea, 0xca, 0xee, 0x15, 0xfb, 0xde, 0x86, 0xdd, 0x14, 0xef, 0x25,
	0x74, 0x56, 0x47, 0x05, 0xfa, 0x7f, 0xee, 0x50, 0xd9, 0x44, 0xb2, 0xf7, 0x37, 0x1b, 0x68, 0xe0,
	0xa3, 0x2f, 0x7e, 0xb9, 0xff, 0x3a, 0x64, 0x07, 0xe7, 0x78, 0x3e, 0x27, 0x17, 0x84, 0xce, 0x83,
	0x83, 0xd0, 0x5f, 0x1e, 0x8a, 0x7f, 0x67, 0x87, 0xe2, 0xf1, 0xa0, 0xfe, 0xb0, 0x9d, 0xd6, 0x85,
	0xee, 0x9b, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x84, 0xf4, 0x9c, 0x37, 0xc8, 0x0d, 0x00, 0x00,
}
